spring:
  application:
    name: Consume Web Service
     
server:
  servlet:
    context-path: /web-poc
  port: 5002

web:
  protocol: http://
  hostname: local.tomcat
  port: null
  context: ws-poc

---
spring:
  profiles: lh

web:
  port: 5001